### PR TITLE
Use common URL schemes for configuration and normalize naming of things

### PR DESCRIPTION
**Pull request by jensschuppe**
This should be straightforward, but due to the size of the commit, I'd like @kainuk or anyone else using this module extensively have a quick look before merging this, just to be sure I didn't miss anything.

### CODE REVIEW

**Comment by jensschuppe** [comment]
@kainuk Do you mind having a quick look? Otherwise I'd just merge it for a new `2.0.0-rc4` pre-release, along with some D9-hardening on the `8.x-dev` branch.

**Comment by kainuk** [comment]
Hi @jensschuppe, the changes make the code a lot more clear. It is a good idea to use CiviMRF on more places in the documentation. I will this install this PR on my test system today.

**Comment by kainuk** [comment]
Hi @jensschuppe, I did an installation and tested it with the cmrf_form_processor. That works fine. So for my most  use case, it is okay (although I should do some renaming myself).

**Comment by kainuk** [comment]
One thing, after an upgrade of the code the report menu has  its old name:
Selection_010
Uninstalling and Reinstalling fixes this. That's an acceptable strategy because this module does not contain data (and it's still dev, so no upgrade path is guaranteed)

**Review by kainuk — APPROVED** [review]
I added my feedback in the comments.

**Comment by jensschuppe** [comment]
Thanks a lot, @kainuk!

**Pull request merged**
